import { ClerkProvider } from '@clerk/nextjs'
import "~/styles/globals.css";
import "@uploadthing/react/styles.css";
import React from "react";
import { Inter, Playfair_Display } from "next/font/google";
import { TopNav } from "~/app/_components/topnav";
import type { Metadata } from "next";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const playfair = Playfair_Display({
    subsets: ["latin"],
    variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Gallery",
  description: "Generated by C. Rosa",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans bg-background text-foreground ${inter.variable} ${playfair.variable}`}>
        <ClerkProvider>
            <div className="h-screen grid grid-rows-[auto_1fr]">
                <TopNav />
                <main className="overflow-y-scroll p-8">
                    {children}
                </main>
            </div>
            {modal}
            <div id="modal-root" />
        </ClerkProvider>
      </body>
    </html>
  );
}
